# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'RNChannelIo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for RNChannelIo
  pod "ChannelIO", :git => 'https://github.com/zoyi/channel-plugin-ios.git', :branch => 'react-native-support'
  pod "React" 
#  rn_path = '../node_modules/react-native'
#  rn_maps_path = '../node_modules/react-native-maps'

  # See http://facebook.github.io/react-native/docs/integration-with-existing-apps.html#configuring-cocoapods-dependencies
#  pod 'React', path: rn_path, subspecs: [
#    'Core',
#    'CxxBridge',
#    'DevSupport',
#    'RCTActionSheet',
#    'RCTAnimation',
#    'RCTGeolocation',
#    'RCTImage',
#    'RCTLinkingIOS',
#    'RCTNetwork',
#    'RCTSettings',
#    'RCTText',
#    'RCTVibration',
#    'RCTWebSocket',
#  ]
end
